# Encoding: utf-8
source 'http://rubygems.org'

group :test do
  gem 'cucumber'
  gem 'rspec-expectations'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'rest-client'
  gem 'byebug'
  gem 'require_all'
  gem 'cucumber-api'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'httparty'
  gem 'json'
  gem "json-schema"
  gem "rack-test", require: "rack/test"
  gem 'chunky_png', '~> 1.3', '>= 1.3.5'
  gem 'chronic'
  gem "sinatra"
  gem "shotgun"
  gem 'fastercsv', '~> 1.5', '>= 1.5.5'
  gem 'timecop'
  gem 'capybara'
  gem 'pretty_face', '~> 0.10.3'
  gem 'rails', '~> 4.2', '>= 4.2.5.1'
  gem 'axlsx', '~> 2.0', '>= 2.0.1'
  gem 'spreadsheet', '~> 1.1', '>= 1.1.2'
  gem 'capybara-screenshot', '~> 1.0', '>= 1.0.13'
  gem 'acts_as_commentable', '~> 4.0', '>= 4.0.2'
  gem 'time_difference', '~> 0.4.2'
  gem 'capybara-angular', '0.2.3'
  gem 'chromedriver-helper'
  gem 'rubyzip', '>= 1.0.0'
  gem 'page-object'
  gem 'capybara-rails'
  gem 'site_prism'
  gem 'phantomjs'
end

