# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1366774636);
user_pref("app.update.lastUpdateTime.background-update-timer", 1366774636);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1366774636);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1366774636);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("browser.migration.version", 6);
user_pref("browser.places.smartBookmarksVersion", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.startup.homepage_override.buildID", "20120614114901");
user_pref("browser.startup.homepage_override.mstone", "13.0.1");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("distribution.MozillaOnline.bookmarksProcessed", true);
user_pref("extensions.addoninstaller.coba@mozilla.com.cn", false);
user_pref("extensions.addoninstaller.fontsetter@mozillaonline.com", false);
user_pref("extensions.addoninstaller.installation.completedtime", "302909932019785627");
user_pref("extensions.addoninstaller.mailnotifier@mozillaonline.com", false);
user_pref("extensions.addoninstaller.muter@yxl.name", false);
user_pref("extensions.addoninstaller.null", false);
user_pref("extensions.addoninstaller.personas@christopher.beard", false);
user_pref("extensions.addoninstaller.shoppingassist@ookong.com", false);
user_pref("extensions.addoninstaller.surveys@mozillaonline.com", false);
user_pref("extensions.addoninstaller.xthunder@lshai.com", false);
user_pref("extensions.addoninstaller.zoompanel@mozillaonline.com", false);
user_pref("extensions.addonnotification.default_rules_version", "0.6");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.cehomepage@mozillaonline.com.install-event-fired", true);
user_pref("extensions.cemigration@mozillaonline.com.install-event-fired", true);
user_pref("extensions.cpmanager@mozillaonline.com.init_time", "1366774305077");
user_pref("extensions.cpmanager@mozillaonline.com.initialized", true);
user_pref("extensions.cpmanager@mozillaonline.com.install-event-fired", true);
user_pref("extensions.cpmanager@mozillaonline.com.prevsessionlen", 1);
user_pref("extensions.cpmanager@mozillaonline.com.show_bookmark_toolbar", false);
user_pref("extensions.cpmanager@mozillaonline.com.update_date", "113/3/24");
user_pref("extensions.cpmanager@mozillaonline.com.uuid", "{733d6469-806d-4c54-8eef-1d5aa15d20cf}");
user_pref("extensions.cpmanager@mozillaonline.com.xpinstall.importlist", false);
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "firebug@software.joehewitt.com:1.7.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:13.0.1");
user_pref("extensions.feedback@mozillaonline.com.installed", true);
user_pref("extensions.firebug.addonBarOpened", true);
user_pref("extensions.firebug.currentVersion", "1.7.3");
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{B7082FAA-CB62-4872-9106-E42DD88EDE45}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\McAfee\\\\SiteAdvisor Enterprise\",\"mtime\":1366771122201}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1365409071361}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"C:\\\\Users\\\\kxu009\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\wskfe2ug.empty\\\\extensions\\\\firebug@software.joehewitt.com.xpi\",\"mtime\":1366780376626}}}]");
user_pref("extensions.installedDistroAddon.cehomepage@mozillaonline.com", true);
user_pref("extensions.installedDistroAddon.cemigration@mozillaonline.com", true);
user_pref("extensions.installedDistroAddon.cpmanager@mozillaonline.com", true);
user_pref("extensions.installedDistroAddon.livemargins@mozillaonline.com", true);
user_pref("extensions.installedDistroAddon.quicklaunch@mozillaonline.com", true);
user_pref("extensions.installedDistroAddon.share_all_cn@mozillaonline.com", true);
user_pref("extensions.installedDistroAddon.tabimprovelite@mozillaonline.com", true);
user_pref("extensions.lastAppVersion", "13.0.1");
user_pref("extensions.lastPlatformVersion", "13.0.1");
user_pref("extensions.livemargins@mozillaonline.com.appcenter.firstRun", false);
user_pref("extensions.livemargins@mozillaonline.com.apps.hideunbookmarkundomsg", "1366774370271-app_shopping");
user_pref("extensions.livemargins@mozillaonline.com.apps.open", "1366774357895-app_stock");
user_pref("extensions.livemargins@mozillaonline.com.apps.showbookmarks", "1366774350665-");
user_pref("extensions.livemargins@mozillaonline.com.apps.unbookmark", "1366774365280-app_shopping");
user_pref("extensions.livemargins@mozillaonline.com.install-event-fired", true);
user_pref("extensions.livemargins@mozillaonline.com.lastVerForUIChange", "5.1.1");
user_pref("extensions.livemargins@mozillaonline.com.manuallyRemovedAppcenterButton", false);
user_pref("extensions.livemargins@mozillaonline.com.manuallyRemovedSnapshotButton", false);
user_pref("extensions.ntabimprovelite.usageSample", "0.14693556170651345");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.quicklaunch@mozillaonline.com.ff4_version", "0.8");
user_pref("extensions.quicklaunch@mozillaonline.com.install-event-fired", true);
user_pref("extensions.share_all_cn@mozillaonline.com.install-event-fired", true);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.tabimprovelite@mozillaonline.com.install-event-fired", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/firebug");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.{B7082FAA-CB62-4872-9106-E42DD88EDE45}.install-event-fired", true);
user_pref("gfx.direct3d.prefer_10_1", true);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1366780376);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1369366603);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
